#pragma once

// ==================================================
// AUTO-GENERATED MODEL FILE
// Do not edit manually.
// Generated by python/train_model.py
// ==================================================

#include <stddef.h>

constexpr int MODEL_INPUT_SIZE = 3;
constexpr int MODEL_HIDDEN_SIZE = 8;

static const char* CLASS_0 = "Moving";
static const char* CLASS_1 = "Still";

static const float INPUT_MEAN[3] = {
    -0.279906250f, 3.589250000f, -6.030625000f
};

static const float INPUT_SCALE[3] = {
    3.017857113f, 4.336667002f, 5.646311759f
};

static const float WEIGHTS_INPUT_HIDDEN[3][8] = {
    { 1.969454932f, -3.645404555f, -5.211271743f, 0.033909560f, 6.110404259f, -0.241534397f, -1.704146178f, 0.904792307f },
    { 10.520195079f, -6.348496341f, -11.053228866f, -0.805302293f, 8.061707650f, 1.008835498f, -7.147926148f, -1.234334873f },
    { -0.598069529f, -3.066424292f, -5.918305842f, -0.540588340f, 2.759610190f, 0.484665782f, -4.768732032f, -0.350530274f },
};

static const float BIAS_HIDDEN[8] = {
    6.029175220f, -1.136543072f, -2.163255327f, -1.905297118f, 12.897261435f, -2.004067155f, -1.052548059f, -0.740156762f
};

static const float WEIGHTS_HIDDEN_OUTPUT[8] = {
    -9.916580398f, 0.725500099f, 9.741889332f, -1.499745246f, -11.193127024f, -0.296647153f, 8.605330759f, 2.767191136f
};

static const float BIAS_OUTPUT = -6.335578201f;
